name: Githab Pages Site CI

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Note:
      # 2024/10/14時点で
      # 'The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3'
      # というWarningが出力されるが、Nodeのバージョン20が強制されるという話で、確認した時点で動作に実害はなさそうなので無視する
      #
      # Refernece:
      # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - name: Install Jekyll and dependencies
        run: gem install jekyll
      - name: Build Jekyll site
        run: jekyll build
      - name: Test Jekyll site
        run: jekyll doctor
